"""agregando producto id a purchase item

Revision ID: 3975ea063abc
Revises: 874dfaf97f7d
Create Date: 2024-12-01 15:06:25.489241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3975ea063abc'
down_revision: Union[str, None] = '874dfaf97f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchaseitem', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchaseitem', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchaseitem', type_='foreignkey')
    op.drop_column('purchaseitem', 'product_id')
    # ### end Alembic commands ###
