"""foreign fix orderitem

Revision ID: 557b8fcb2323
Revises: 9989dc057de9
Create Date: 2024-12-01 12:53:58.684268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557b8fcb2323'
down_revision: Union[str, None] = '9989dc057de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('productvariant_id', sa.Integer(), nullable=False))
    op.drop_constraint('orderitem_product_id_fkey', 'orderitem', type_='foreignkey')
    op.create_foreign_key(None, 'orderitem', 'productvariant', ['productvariant_id'], ['id'])
    op.drop_column('orderitem', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.create_foreign_key('orderitem_product_id_fkey', 'orderitem', 'product', ['product_id'], ['id'])
    op.drop_column('orderitem', 'productvariant_id')
    # ### end Alembic commands ###
