"""quitar color 2 productvariant

Revision ID: 69f10ab64b70
Revises: 093e199c4a85
Create Date: 2024-11-30 20:15:25.834031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f10ab64b70'
down_revision: Union[str, None] = '093e199c4a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productvariant', 'color2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productvariant', sa.Column('color2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
